### ISSUE TITLE
Arm64 images

### ISSUE THREAD

**Issue by cyberi0n** [limepepper/ansible-role-raspberrypi#20]
What are the steps taken to support the existing armhf images? Would love to add support for arm64 variants.

**Comment by tolland** [comment]
I've not had a chance to look at these images. what is their purpose?

but if they follow similar conventions as the vanilla images, it might just work out of the box. (i.e. cmdline.txt and 2 partitions etc)

**Comment by tolland** [comment]
I've tested with the arm64 and they seem to build ok. There are some magnet links to pre-built images in the [downloads page of the wiki.](https://github.com/limepepper/raspberry-pi-factory-reset/wiki/Downloads#raspios-arm64-images)

If you pull the current develop, you can build it like so:

## option 1 - build lite image

download the [lite image](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip) only, and unzip it , then build it

    $ sudo ./create-factory-reset -a \
                 -i ./sources/2021-05-07-raspios-buster-arm64-lite.img

this will output a new image in the `./build` directory:

    build/2021-05-07-raspios-buster-arm64-lite.restore.img


## option 2 - build desktop image

download [desktop image](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/2021-05-07-raspios-buster-arm64.zip) , and unzip it, and provide path as option like so:

```
$ sudo ./create-factory-reset -a \
    -i ./sources/2021-05-07-raspios-buster-arm64.img
```

So the interesting thing to note here, is that the resulting image is very big:

```
$ ls -lah build/

-rw-r--r--.  1 root      root      7.2G Oct 30 05:15 2021-05-07-raspios-buster-arm64.restore.img
```

**The image is 7.2G in size** because it contains 2 copies of the desktop image root partition




## option 3 - build desktop image using lite image for recovery partition

download both [desktop image](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/2021-05-07-raspios-buster-arm64.zip)  and the [lite image](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/2021-05-07-raspios-buster-arm64-lite.zip), and unzip both, and provide them as options like so:

```
$ sudo ./create-factory-reset -a \
    -i ./sources/2021-05-07-raspios-buster-arm64.img 
    -l ./sources/2021-05-07-raspios-buster-arm64-lite.img
```

**Note: now the image is a couple of GB smaller**

```
$ ls -lah build/

-rw-r--r--.  1 root      root      5.6G Oct 30 04:41 2021-05-07-raspios-buster-arm64.restore.img
```
