### ISSUE TITLE
image doesnt load on pi

### ISSUE THREAD

**Issue by JamesM92** [limepepper/ansible-role-raspberrypi#7]
So i have a custom image i made, which i used pi-shrink to reduce down. (this custom image reimages a pi fine)

I can run the factory reset fine and it creates the restore img. but when i load it on the pi it never fully loads.

**Comment by tolland** [comment]
I guess the first step is to see if the image that was created can be restored separately from the factory restore process.

Also, it would be helpful to provide hardware and source image information.

(I've not tested this for at least a year, and haven't tested with recent versions, so to some degree this is just a guide, rather than step by step instructions)
